### PR TITLE
fix tests failing with AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

### LINKED ISSUE #810: [Bug]: Tests failing with AttributeError: 'numpy.ndarray' object has no attribute 'toarray'
### Python Version

3.12.11

### Describe the bug

Several tests are failing with AttributeError: 'numpy.ndarray' object has no attribute 'toarray'. I originally encountered the issue when testing my local development installation of PyBOP, but the tests are also failing in the GitHub actions for the PyBOP repository. 

The problem can be fixed by changing one line of code (https://github.com/pybop-team/PyBOP/blob/develop/pybop/problems/fitting_problem.py#L200) to 

```
s: sol[s].sensitivities[p].reshape(-1)
```
(I will add the corresponding PR shortly).

I have identified the first time the error started appearing in the GitHub actions (https://github.com/pybop-team/PyBOP/actions/runs/16736403316) which suggests that a change to PyBAMM has introduced the issue. Based on the PyBAMM changelog, the issue seems to be caused by https://github.com/pybamm-team/PyBaMM/pull/5037.

### Steps to reproduce the behaviour

With a developer installation of the PyBOP develop branch, run
```
nox -s quick
```

This issue also appears in the github actions for the PyBOP repository (first occurance develop branch: https://github.com/pybop-team/PyBOP/actions/runs/16736403316)

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by SarahRo**
# Description

Fixes tests failing with AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

Fixes #810 

## Type of change

Bugfix

# Important checks:

Please confirm the following before marking the PR as ready for review:
- No style issues: `$ pre-commit run` or `$ nox -s pre-commit` (see [CONTRIBUTING.md](https://github.com/pybop-team/PyBOP/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- All tests pass: `nox -s tests`
- The documentation builds: `nox -s doctest`
- Code is commented for hard-to-understand areas
- Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by NicolaCourtier** [comment]
Superseded by the restructure, so I'll close this one, thanks Sarah.
