### ISSUE TITLE
[Bug]: Tests failing with AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

### ISSUE THREAD

**Issue by SarahRo** [pybop-team/PyBOP#810]
### Python Version

3.12.11

### Describe the bug

Several tests are failing with AttributeError: 'numpy.ndarray' object has no attribute 'toarray'. I originally encountered the issue when testing my local development installation of PyBOP, but the tests are also failing in the GitHub actions for the PyBOP repository. 

The problem can be fixed by changing one line of code (https://github.com/pybop-team/PyBOP/blob/develop/pybop/problems/fitting_problem.py#L200) to 

```
s: sol[s].sensitivities[p].reshape(-1)
```
(I will add the corresponding PR shortly).

I have identified the first time the error started appearing in the GitHub actions (https://github.com/pybop-team/PyBOP/actions/runs/16736403316) which suggests that a change to PyBAMM has introduced the issue. Based on the PyBAMM changelog, the issue seems to be caused by https://github.com/pybamm-team/PyBaMM/pull/5037.

### Steps to reproduce the behaviour

With a developer installation of the PyBOP develop branch, run
```
nox -s quick
```

This issue also appears in the github actions for the PyBOP repository (first occurance develop branch: https://github.com/pybop-team/PyBOP/actions/runs/16736403316)

### Relevant log output

```shell

```

**Comment by SarahRo** [comment]
Fix does not work with Python 3.9 (since PyBaMM deprecated Python 3.9 before the change that introduced the error).
