### ISSUE TITLE
module 'pybop' has no attribute 'plot'

### ISSUE THREAD

**Issue by Santiagopeacely** [pybop-team/PyBOP#553]
This  is why？ 
![image](https://github.com/user-attachments/assets/67483726-fe93-4949-bf8b-0f0d8ae0f2d1)

**Comment by BradyPlanden** [comment]
Hi @Santiagopeacely, we've recently changed the plotting methods in the `develop` branch, which will released in the next version. The examples in the `develop` branch won't work with PyBOP v24.9.1 or previous as this change is breaking. For the examples that use the correct plotting methods, following these [examples](https://github.com/pybop-team/PyBOP/tree/main/examples) until the next PyBOP release.

**Comment by Santiagopeacely** [comment]
That‘s great! Thank you
